CessnaJ/LOTBOOK2

src/main/java/lotbook/lotbook/controller/CheckoutController.java
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp

💛 [FEAT] checkoutbuynow.jsp 구현

---

src/main/java/lotbook/lotbook/controller/ProductDetailController.java
src/main/java/lotbook/lotbook/controller/SearchController.java
src/main/java/lotbook/lotbook/dto/mapper/CategoryMapperDTO.java
src/main/java/lotbook/lotbook/dto/mapper/CategoryProductWithReviewDTO.java
src/main/java/lotbook/lotbook/dto/mapper/ProductRelatedNameMapperDTO.java
src/main/java/lotbook/lotbook/dto/mapper/ReviewWithNameMapperDTO.java
src/main/java/lotbook/lotbook/dto/mapper/SearchProductMapperDTO.java
src/main/java/lotbook/lotbook/dto/response/ProductDetailWithReviews.java
src/main/java/lotbook/lotbook/dto/response/SearchResult.java
src/main/java/lotbook/lotbook/repository/CategoryMapper.java
src/main/java/lotbook/lotbook/repository/ProductMapper.java
src/main/java/lotbook/lotbook/repository/ReviewMapper.java
src/main/java/lotbook/lotbook/repository/SearchMapper.java
src/main/java/lotbook/lotbook/service/ProductService.java
src/main/java/lotbook/lotbook/service/ProductServiceImpl.java
src/main/java/lotbook/lotbook/service/SearchService.java
src/main/java/lotbook/lotbook/service/SearchServiceImpl.java
src/main/resources/mappers/CategoryMapper.xml
src/main/resources/mappers/ProductMapper.xml
src/main/resources/mappers/ReviewMapper.xml
src/main/resources/mappers/SearchMapper.xml
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp

- 세부사항을 항목으로 설명
http://localhost:8080/search?keyword=%EC%9E%90%EB%B0%94
넣었을때 결과
http://localhost:8080/product-detail/1
넣었을때 결과
다른 링크로 넘어가는곳도 고쳐야하는 상황입니다.

✈ [FEAT] 상품상세조회, 기본 검색기능

---

src/main/java/lotbook/lotbook/repository/ProductMapper.java
src/main/java/lotbook/lotbook/service/ProductService.java
src/main/java/lotbook/lotbook/service/ProductServiceImpl.java

✈ [CHORE] merge 흔적 제거

---

src/main/java/lotbook/lotbook/service/ProductServiceImpl.java

✈ [CHORE] 괄호 추가

---

src/main/java/lotbook/lotbook/controller/CartController.java
src/main/java/lotbook/lotbook/service/OrderDetailService.java
src/main/resources/mappers/OrderMapper.xml
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FEAT] 장바구니에서 구매 - 카카오페이 결제

---

src/main/java/lotbook/lotbook/controller/CartController.java
src/main/java/lotbook/lotbook/service/OrderDetailServiceImpl.java
src/main/java/lotbook/lotbook/service/PointService.java
src/main/java/lotbook/lotbook/service/PointServiceImpl.java

🎈 [FEAT] CRUD 명칭 통일

---

src/main/java/lotbook/lotbook/controller/CartController.java
src/main/java/lotbook/lotbook/controller/MypageController.java
src/main/webapp/WEB-INF/views/404.jsp
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/popup.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FEAT] 마이페이지 & 마이페이지 장바구니 완료

---

src/main/java/lotbook/lotbook/controller/MainController.java
src/main/java/lotbook/lotbook/controller/MypageController.java
src/main/java/lotbook/lotbook/controller/PageController.java
src/main/webapp/WEB-INF/views/404.jsp
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp
src/main/webapp/WEB-INF/views/signin.jsp
src/main/webapp/WEB-INF/views/signup.jsp

🎈 [FIX] 장바구니 개수 오류 해결

---

src/main/java/lotbook/lotbook/controller/CartController.java
src/main/java/lotbook/lotbook/controller/CheckoutController.java
src/main/java/lotbook/lotbook/repository/OrderDetailMapper.java
src/main/java/lotbook/lotbook/service/OrderDetailService.java
src/main/java/lotbook/lotbook/service/OrderDetailServiceImpl.java
src/main/java/lotbook/lotbook/service/PointService.java
src/main/java/lotbook/lotbook/service/PointServiceImpl.java
src/main/resources/mappers/OrderDetailMapper.xml
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp

OrderDetailResponse 는 테스트로 찍어서 같이 첨부했습니당

💛 [FEAT] checkout-result 구현

---

src/main/java/lotbook/lotbook/controller/CheckoutController.java
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp

💛 [FEAT] checkout result 카트에서 구매와 바로 구매 분리

---

src/main/java/lotbook/lotbook/controller/AxiosController.java
src/main/java/lotbook/lotbook/controller/MemberController.java
src/main/java/lotbook/lotbook/repository/MemberMapper.java
src/main/java/lotbook/lotbook/service/MemberService.java
src/main/java/lotbook/lotbook/service/MemberServiceImpl.java
src/main/resources/mappers/MemberMapper.xml
src/main/webapp/WEB-INF/views/signup.jsp

😀[FEAT]: 회원가입

---

src/main/java/lotbook/lotbook/controller/CheckoutController.java

💛 [FEAT] 구매할인 적용

---

src/main/java/lotbook/lotbook/controller/CartController.java

🎈 [FIX] 구매 상품 총 금액 오류 해결

---

src/main/java/lotbook/lotbook/controller/MemberController.java
src/main/java/lotbook/lotbook/enums/ErrorCode.java
src/main/java/lotbook/lotbook/service/CartServiceImpl.java
src/main/webapp/WEB-INF/views/error.jsp

🎈 [FEAT] 장바구니 에러 관리

---

src/main/java/lotbook/lotbook/enums/ErrorCode.java
src/main/java/lotbook/lotbook/service/OrderDetailServiceImpl.java
src/main/java/lotbook/lotbook/service/OrderServiceImpl.java

💛 [FEAT] 주문관련 에러코드 추가

---

src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FIX] 장바구니 재고 부족 에러 해결

---

src/main/java/lotbook/lotbook/controller/MainController.java
src/main/java/lotbook/lotbook/controller/MemberController.java
src/main/java/lotbook/lotbook/controller/ReviewController.java
src/main/java/lotbook/lotbook/dto/request/ReviewRequest.java
src/main/java/lotbook/lotbook/repository/MemberMapper.java
src/main/java/lotbook/lotbook/repository/ReviewMapper.java
src/main/java/lotbook/lotbook/service/MemberService.java
src/main/java/lotbook/lotbook/service/MemberServiceImpl.java
src/main/java/lotbook/lotbook/service/OrderService.java
src/main/java/lotbook/lotbook/service/ReviewService.java
src/main/java/lotbook/lotbook/service/ReviewServiceImpl.java
src/main/resources/mappers/MemberMapper.xml
src/main/resources/mappers/ReviewMapper.xml
src/main/webapp/WEB-INF/views/404.jsp
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp
src/main/webapp/WEB-INF/views/signin.jsp
src/main/webapp/WEB-INF/views/signup.jsp

😀[FEAT]: 마이페이지

---

src/main/java/lotbook/lotbook/repository/MemberMapper.java
src/main/java/lotbook/lotbook/service/MemberServiceImpl.java
src/main/resources/mappers/MemberMapper.xml
src/main/webapp/WEB-INF/views/checkout.jsp

😀[REFACTOR]: 회원정보 mapper 코드 수정

---

src/main/java/lotbook/lotbook/controller/MainController.java
src/main/java/lotbook/lotbook/controller/MypageController.java
src/main/java/lotbook/lotbook/repository/OrderDetailMapper.java
src/main/java/lotbook/lotbook/repository/ProductMapper.java
src/main/java/lotbook/lotbook/repository/ReviewMapper.java
src/main/java/lotbook/lotbook/service/OrderDetailService.java
src/main/java/lotbook/lotbook/service/OrderDetailServiceImpl.java
src/main/java/lotbook/lotbook/service/ProductService.java
src/main/java/lotbook/lotbook/service/ProductServiceImpl.java
src/main/java/lotbook/lotbook/service/ReviewService.java
src/main/java/lotbook/lotbook/service/ReviewServiceImpl.java
src/main/resources/mappers/OrderDetailMapper.xml
src/main/resources/mappers/ProductMapper.xml
src/main/resources/mappers/ReviewMapper.xml
src/main/webapp/WEB-INF/views/404.jsp
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FEAT] 마이페이지 주문 상태 변경

---

src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FIX] 재고 없는 상품 비활성화

---

src/main/java/lotbook/lotbook/controller/CartController.java

🎈 [FIX] 장바구니 주문 가격 에러 수정

---

src/main/java/lotbook/lotbook/controller/CheckoutController.java
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/mypage.jsp

🎈 [FIX] 주문 완료 후 결제 금액 오류 해결

---

src/main/webapp/WEB-INF/views/404.jsp
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp
src/main/webapp/WEB-INF/views/signin.jsp
src/main/webapp/WEB-INF/views/signup.jsp

🎈 [FIX] 네비바 홈 태그 오류 수정

---

src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/signin.jsp
src/main/webapp/WEB-INF/views/signup.jsp

😀[Refactor]: mypage URL 경로 수정

---

src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

✈ [CHORE] home link href들 변경

---

src/main/java/lotbook/lotbook/controller/MemberController.java
src/main/java/lotbook/lotbook/controller/MypageController.java
src/main/java/lotbook/lotbook/repository/MemberMapper.java
src/main/java/lotbook/lotbook/service/MemberService.java
src/main/java/lotbook/lotbook/service/MemberServiceImpl.java
src/main/resources/mappers/MemberMapper.xml

😀[FIX]: 회원정보 수정 오류 해결

---

src/main/java/lotbook/lotbook/controller/AxiosController.java
src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FEAT] 통합 검색 검색창 리스트 구현

---

src/main/webapp/WEB-INF/views/category.jsp
src/main/webapp/WEB-INF/views/checkout-result.jsp
src/main/webapp/WEB-INF/views/checkout.jsp
src/main/webapp/WEB-INF/views/checkoutbuynow.jsp
src/main/webapp/WEB-INF/views/contact.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/member-info-login.jsp
src/main/webapp/WEB-INF/views/member-info.jsp
src/main/webapp/WEB-INF/views/mypage.jsp
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/WEB-INF/views/shop-details.jsp
src/main/webapp/WEB-INF/views/shoping-cart.jsp

🎈 [FIX] 선택 시 검색창 초기화

---

src/main/webapp/WEB-INF/views/search.jsp

✈  [FEAT] search pagination 처리
